Use Printf instead

diff --git a/.github/workflows/ccpp.yml b/.github/workflows/ccpp.yml
--- a/.github/workflows/ccpp.yml
+++ b/.github/workflows/ccpp.yml
@@ -15,7 +15,7 @@ jobs:
 
     - name: Ensure ./nuklear.h matches sources
       run: |
-        git diff --exit-code nuklear.h || (echo "Error: nuklear.h does not match sources. To fix:\n1. Apply changes to ./src/*\n2. Rebuild with 'make nuke'" && exit 1)
+        git diff --exit-code nuklear.h || (printf "\nError: nuklear.h does not match sources. To fix:\n1. Apply changes to ./src/*\n2. Rebuild with 'make nuke'\n" && exit 1)
 
     - name: apt-update
       run: sudo apt-get update -qq
